### ISSUE TITLE
Create a chat command where the viewer can discover how long the current stream has been up.

### ISSUE THREAD

**Issue by B0tzerker** [pulcher/TalkingHead#53]
Typically this command is called uptime and is possible through a bots such as nightbot and moobot. It's not a default command so either the streamer or a mod will have to create it with the chat code:

__!addcom !uptime The channel has been live since: $(twitch.tv/haroldpulcher "{{uptimeLength}}")__

Naturally those bots reveal the length of time in chat as text. However, it would be cool if MrBigHeadBot could say how long the stream has been up.

**Comment by pulcher** [comment]
Cool.  will look into this.  Great addon.
