### ISSUE TITLE
Update MBH so MBH will say current schedule when asked.

### ISSUE THREAD

**Issue by B0tzerker** [pulcher/TalkingHead#58]
Most streamers have their streaming schedule posted below the stream on the channel page. Others have it as a command where bots like nightbot, moobot, and streamlabs will either periodically post the schedule in chat or when triggered by a command such as !schedule. Since you do not use any of those bots, it would be cool to have MBH say the schedule when asked.

**Comment by pulcher** [comment]
I am sure the twitch api would give me access to the schedule. 

I am almost positive that mbh can listen to a !schedule and not have to put the !mbh in front of it.

Great suggestion.

**Comment by pulcher** [comment]
Yo @B0tzerker, look what I found..... https://github.com/TwitchLib/TwitchLib.Api/blob/master/TwitchLib.Api.Helix/Schedule.cs

Seems we are gonna need to crack open the Api for this one....

**Comment by pulcher** [comment]
Implemented the command to put the next stream in to chat.
