### ISSUE TITLE
I'm able to post links in chat, recommend such activity for streamer/mods/VIPs only.

### ISSUE THREAD

**Issue by B0tzerker** [pulcher/TalkingHead#60]
Allowing only streamer/mods/VIPs to post links in chat will prevent trolls from spamming links in chat. And such links could be links to porn sites. Typically this security enforcement is handled by nightbot or moobot, so adding this feature to MBH will make it more rebust.

**Comment by pulcher** [comment]
Ok, I should be able to detect those links and do something fun with them.   

Great suggestion.
