### ISSUE TITLE
MBH chat command, "!mbh readlc"

### ISSUE THREAD

**Issue by B0tzerker** [pulcher/TalkingHead#69]
This command would trigger Mr Big Head to read the last comment made in chat. The idea behind this command is for when viewers have made a comment for Harold Pulchers attention and realized they need MBH to read it in order to get Harolds attention faster. The simple version of the command can have MBH read the last comment in chat or an advanced version of the command can have MBH read the last comment by the viewer entering the command, "!mbh readlc"

**Comment by pulcher** [comment]
From hugo(and we thought it was cool):
!mbh speaklast

**Comment by pulcher** [comment]
Look for a stack class, and keep the last 20 chats
Pop off the last chat received
Only save chats from users.... not Annoucements, Mods, VIPS
Only from non-subs, and the such.  This is so a Mod, VIP, or other Sub can use this command to say the words.
